/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FromSi (https://sketchfab.com/fromsi665)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/4cc7c1bf585f4b929ddd32f6cab3ba58
title: RUBIK'S CUBE
*/

import * as React from "react";
import * as THREE from "three";
import { useRef, useState, useEffect } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";

// import { useAnimations } from "@react-three/drei/useAnimations";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Cube001_Cube_0: THREE.Mesh;
    Cube000_Cube_0: THREE.Mesh;
    Cube086_Yellow_0: THREE.Mesh;
    Cube085_Yellow_0: THREE.Mesh;
    Cube084_Yellow_0: THREE.Mesh;
    Cube083_Yellow_0: THREE.Mesh;
    Cube082_Yellow_0: THREE.Mesh;
    Cube081_Yellow_0: THREE.Mesh;
    Cube080_Yellow_0: THREE.Mesh;
    Cube079_Yellow_0: THREE.Mesh;
    Cube078_Yellow_0: THREE.Mesh;
    Cube077_White_0: THREE.Mesh;
    Cube076_White_0: THREE.Mesh;
    Cube075_White_0: THREE.Mesh;
    Cube074_White_0: THREE.Mesh;
    Cube073_White_0: THREE.Mesh;
    Cube072_White_0: THREE.Mesh;
    Cube071_White_0: THREE.Mesh;
    Cube070_White_0: THREE.Mesh;
    Cube069_White_0: THREE.Mesh;
    Cube068_Blue_0: THREE.Mesh;
    Cube067_Blue_0: THREE.Mesh;
    Cube066_Blue_0: THREE.Mesh;
    Cube065_Blue_0: THREE.Mesh;
    Cube064_Blue_0: THREE.Mesh;
    Cube063_Blue_0: THREE.Mesh;
    Cube062_Blue_0: THREE.Mesh;
    Cube061_Blue_0: THREE.Mesh;
    Cube059_Blue_0: THREE.Mesh;
    Cube058_Orange_0: THREE.Mesh;
    Cube057_Orange_0: THREE.Mesh;
    Cube056_Orange_0: THREE.Mesh;
    Cube055_Orange_0: THREE.Mesh;
    Cube054_Orange_0: THREE.Mesh;
    Cube053_Orange_0: THREE.Mesh;
    Cube052_Orange_0: THREE.Mesh;
    Cube051_Orange_0: THREE.Mesh;
    Cube050_Orange_0: THREE.Mesh;
    Cube049_Green_0: THREE.Mesh;
    Cube048_Green_0: THREE.Mesh;
    Cube047_Green_0: THREE.Mesh;
    Cube046_Green_0: THREE.Mesh;
    Cube045_Green_0: THREE.Mesh;
    Cube044_Green_0: THREE.Mesh;
    Cube043_Green_0: THREE.Mesh;
    Cube042_Green_0: THREE.Mesh;
    Cube039_Green_0: THREE.Mesh;
    Cube034_Red_0: THREE.Mesh;
    Cube040_Red_0: THREE.Mesh;
    Cube036_Red_0: THREE.Mesh;
    Cube041_Red_0: THREE.Mesh;
    Cube038_Red_0: THREE.Mesh;
    Cube033_Red_0: THREE.Mesh;
    Cube037_Red_0: THREE.Mesh;
    Cube035_Red_0: THREE.Mesh;
    Cube060_Red_0: THREE.Mesh;
    Cube032_Cube_0: THREE.Mesh;
    Cube031_Cube_0: THREE.Mesh;
    Cube030_Cube_0: THREE.Mesh;
    Cube029_Cube_0: THREE.Mesh;
    Cube027_Cube_0: THREE.Mesh;
    Cube026_Cube_0: THREE.Mesh;
    Cube025_Cube_0: THREE.Mesh;
    Cube024_Cube_0: THREE.Mesh;
    Cube023_Cube_0: THREE.Mesh;
    Cube022_Cube_0: THREE.Mesh;
    Cube021_Cube_0: THREE.Mesh;
    Cube020_Cube_0: THREE.Mesh;
    Cube019_Cube_0: THREE.Mesh;
    Cube018_Cube_0: THREE.Mesh;
    Cube017_Cube_0: THREE.Mesh;
    Cube016_Cube_0: THREE.Mesh;
    Cube015_Cube_0: THREE.Mesh;
    Cube014_Cube_0: THREE.Mesh;
    Cube012_Cube_0: THREE.Mesh;
    Cube011_Cube_0: THREE.Mesh;
    Cube010_Cube_0: THREE.Mesh;
    Cube009_Cube_0: THREE.Mesh;
    Cube008_Cube_0: THREE.Mesh;
    Cube007_Cube_0: THREE.Mesh;
  };
  materials: {
    Cube: THREE.MeshStandardMaterial;
    Yellow: THREE.MeshStandardMaterial;
    White: THREE.MeshStandardMaterial;
    Blue: THREE.MeshStandardMaterial;
    Orange: THREE.MeshStandardMaterial;
    Green: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
  };
};

type ActionName = "Scene";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF("/cube.gltf") as GLTFResult;
  // const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube001_Cube_0.geometry}
              />
            </group>
            <group
              position={[0, 0, -0.46]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube000_Cube_0.geometry}
              />
            </group>
            <group rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube086_Yellow_0.geometry}
              />
            </group>
            <group rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube085_Yellow_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI, 0, -Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube084_Yellow_0.geometry}
              />
            </group>
            <group rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube083_Yellow_0.geometry}
              />
            </group>
            <group rotation={[0, -1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube082_Yellow_0.geometry}
              />
            </group>
            <group rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube081_Yellow_0.geometry}
              />
            </group>
            <group rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube080_Yellow_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI, 0, -Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube079_Yellow_0.geometry}
              />
            </group>
            <group rotation={[Math.PI, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Yellow}
                geometry={nodes.Cube078_Yellow_0.geometry}
              />
            </group>
            <group rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube077_White_0.geometry}
              />
            </group>
            <group rotation={[0, 0, Math.PI / 2]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube076_White_0.geometry}
              />
            </group>
            <group rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube075_White_0.geometry}
              />
            </group>
            <group rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube074_White_0.geometry}
              />
            </group>
            <group rotation={[0, 1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube073_White_0.geometry}
              />
            </group>
            <group rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube072_White_0.geometry}
              />
            </group>
            <group rotation={[0, 0, Math.PI / 2]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube071_White_0.geometry}
              />
            </group>
            <group rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube070_White_0.geometry}
              />
            </group>
            <group rotation={[0, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.White}
                geometry={nodes.Cube069_White_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube068_Blue_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube067_Blue_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube066_Blue_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube065_Blue_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube064_Blue_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube063_Blue_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube062_Blue_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube061_Blue_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Blue}
                geometry={nodes.Cube059_Blue_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube058_Orange_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI, -1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube057_Orange_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube056_Orange_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube055_Orange_0.geometry}
              />
            </group>
            <group rotation={[Math.PI, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube054_Orange_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube053_Orange_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI, -1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube052_Orange_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube051_Orange_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Orange}
                geometry={nodes.Cube050_Orange_0.geometry}
              />
            </group>
            <group rotation={[Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube049_Green_0.geometry}
              />
            </group>
            <group rotation={[Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube048_Green_0.geometry}
              />
            </group>
            <group
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube047_Green_0.geometry}
              />
            </group>
            <group rotation={[Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube046_Green_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube045_Green_0.geometry}
              />
            </group>
            <group rotation={[Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube044_Green_0.geometry}
              />
            </group>
            <group rotation={[Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube043_Green_0.geometry}
              />
            </group>
            <group
              rotation={[Math.PI / 2, 0, -Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube042_Green_0.geometry}
              />
            </group>
            <group rotation={[Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Green}
                geometry={nodes.Cube039_Green_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube034_Red_0.geometry}
              />
            </group>
            <group rotation={[0, 1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube040_Red_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube036_Red_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube041_Red_0.geometry}
              />
            </group>
            <group rotation={[Math.PI / 2, 0, Math.PI]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube038_Red_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube033_Red_0.geometry}
              />
            </group>
            <group rotation={[0, 1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube037_Red_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube035_Red_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.material}
                geometry={nodes.Cube060_Red_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube032_Cube_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube031_Cube_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube030_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube029_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube027_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube026_Cube_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube025_Cube_0.geometry}
              />
            </group>
            <group rotation={[0, 1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube024_Cube_0.geometry}
              />
            </group>
            <group rotation={[0, 1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube023_Cube_0.geometry}
              />
            </group>
            <group rotation={[0, 1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube022_Cube_0.geometry}
              />
            </group>
            <group rotation={[0, 1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube021_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube020_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube019_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube018_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube017_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube016_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube015_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube014_Cube_0.geometry}
              />
            </group>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube012_Cube_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube011_Cube_0.geometry}
              />
            </group>
            <group rotation={[0, 1.57, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube010_Cube_0.geometry}
              />
            </group>
            <group rotation={[Math.PI, 0, 0]} scale={[100, 100, 100]}>
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube009_Cube_0.geometry}
              />
            </group>
            <group
              rotation={[-Math.PI / 2, Math.PI / 2, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube008_Cube_0.geometry}
              />
            </group>
            <group
              name="Cube007"
              rotation={[0, 1.57, 0]}
              scale={[100, 100, 100]}
            >
              <mesh
                castShadow
                receiveShadow
                material={materials.Cube}
                geometry={nodes.Cube007_Cube_0.geometry}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/cube.gltf");
