/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FromSi (https://sketchfab.com/fromsi665)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/4cc7c1bf585f4b929ddd32f6cab3ba58
title: RUBIK'S CUBE
*/

import * as React from "react";
import * as THREE from "three";
import { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

import { GLTFResult } from "./CubeTypes";
import { getConfig } from "./CubeConstants";
import { CubeRotator } from "./CubeRotator";
import {
  useCubeViewRotation,
  useLeanFlags,
} from "../../hooks/useCubeViewRotation";

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const result = useGLTF("/cube.gltf") as GLTFResult;

  const flags = useLeanFlags();
  const rotation = useCubeViewRotation(flags, group.current?.rotation);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[rotation.x, rotation.y, rotation.z]}
    >
      <group position={[0, 0, 0]} rotation={[-Math.PI, 0, -Math.PI / 2]}>
        <CubeRotator config={getConfig(result)} />
      </group>
    </group>
  );
}

useGLTF.preload("/cube.gltf");
